name: Build, Test & Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_test_deploy:
    env:
      INPUT_TOKEN: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: 📥 Get latest source code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.PUBLISH_PAT }}
      - name: 🔧 Setup .npmrc file
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: 🗑️ Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: 🔄 Restore yarn cahce
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: 📦 Install packages using yarn
        run: yarn install
      - name: 🧪 Test using @testing-library/react-hooks
        run: yarn run test
      - name: 🏗️ Build main package using rollup
        run: yarn run build
      - name: 🚚 Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/main/package.json
      - name: 🏗️ Build example app using react-scripts
        run: yarn run build:example
      - name: 🚀 Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: packages/examples/build/
