name: Test, Build & Deploy
on:
  push:
    branches: [ feat/npmworkspaces ]
  pull_request:
    branches: [ main ]
jobs:
  test_build_deploy:
    env:
      CI: true
      GENERATE_SOURCEMAP: false
      INPUT_TOKEN: ''
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 15.x ]
    steps:
      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: 📥 Get latest source code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 🔄 Restore npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: 📦 Install dependencies
        run: npm install
      - name: 🧪 Run tests suite
        run: npm run test
      - name: 🏗️ Build main package
        run: npm run build
      - name: 🚚 Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/main/package.json
      - name: 🏗️ Build example app
        run: npm run build:example
      - name: 🚀 Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: packages/examples/build/
